version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install --save --legacy-peer-deps
      - run:
          name: Run Tests
          command: npm run test
